version: '3.2'

services:
   db:
      image: mysql:8.0
      container_name: appsDB
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
     
   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db
        UPLOAD_LIMIT: 1G

      
      #   docker-compose -f dockerphpmysql.yml up -d 
      #  docker exec -it appsDB mysql -uroot -proot
      # update mysql.user set host = ‘%’ where user=’root’;
      #  ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
      # SELECT user,host FROM mysql.user;
        